"""HTTP endpoints for the MITM capture: list flows, inspect one, download CA."""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

from app.config import settings
from app.proxy import FlowRepository

router = APIRouter(prefix="/api/proxy", tags=["proxy"])

_repo = FlowRepository()

# mitmproxy writes its CA to ~/.mitmproxy by default. We pass --set confdir=/data/mitm
# in entrypoint.sh so the cert ends up in a predictable location users can grab.
CA_DIR = Path("/data/mitm")


@router.get("/status")
async def status() -> dict:
    """High-level view for the UI: is the proxy reachable, how many flows we have."""
    total = await _repo.count_flows()
    ca_path = CA_DIR / "mitmproxy-ca-cert.pem"
    return {
        "listen_port": settings.mitm_port,
        "flows_captured": total,
        "ca_available": ca_path.exists(),
        "storage": "postgres",
    }


@router.get("/hosts")
async def hosts() -> list:
    """Distinct hosts seen, with per-host counts. Used for UI filters."""
    return await _repo.list_hosts()


@router.get("/flows")
async def flows(
    limit: int = Query(default=200, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
    host: Optional[str] = None,
    method: Optional[str] = None,
    status_min: Optional[int] = Query(default=None, ge=100, le=599),
    status_max: Optional[int] = Query(default=None, ge=100, le=599),
    search: Optional[str] = Query(default=None, description="Substring match on URL"),
) -> dict:
    items = await _repo.list_flows(
        limit=limit,
        offset=offset,
        host=host,
        method=method,
        status_min=status_min,
        status_max=status_max,
        search=search,
    )
    total = await _repo.count_flows()
    return {
        "total": total,
        "count": len(items),
        "offset": offset,
        "limit": limit,
        "items": [item.to_dict() for item in items],
    }


@router.get("/flows/{flow_id}")
async def flow_detail(flow_id: str) -> dict:
    flow = await _repo.get_flow(flow_id)
    if flow is None:
        raise HTTPException(status_code=404, detail="flow not found")
    return flow


@router.delete("/flows")
async def clear_flows() -> dict:
    deleted = await _repo.delete_all()
    return {"deleted": deleted}


@router.get("/ca.pem")
async def download_ca() -> FileResponse:
    """Browser trust-store CA cert generated by mitmproxy on first start."""
    ca_path = CA_DIR / "mitmproxy-ca-cert.pem"
    if not ca_path.exists():
        raise HTTPException(
            status_code=404,
            detail=(
                "CA certificate not generated yet. Send any HTTPS request "
                "through the proxy once, then retry."
            ),
        )
    return FileResponse(
        path=str(ca_path),
        media_type="application/x-pem-file",
        filename="syphax-mitmproxy-ca.pem",
    )
